/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItItIndexRouteImport } from './routes/it-it/index'
import { Route as ApiPublicGoIdRouteImport } from './routes/api/public/go.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItItIndexRoute = ItItIndexRouteImport.update({
  id: '/it-it/',
  path: '/it-it/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoIdRoute = ApiPublicGoIdRouteImport.update({
  id: '/api/public/go/$id',
  path: '/api/public/go/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/it-it/': typeof ItItIndexRoute
  '/api/public/go/$id': typeof ApiPublicGoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/it-it': typeof ItItIndexRoute
  '/api/public/go/$id': typeof ApiPublicGoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/it-it/': typeof ItItIndexRoute
  '/api/public/go/$id': typeof ApiPublicGoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/it-it/' | '/api/public/go/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/it-it' | '/api/public/go/$id'
  id: '__root__' | '/' | '/it-it/' | '/api/public/go/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ItItIndexRoute: typeof ItItIndexRoute
  ApiPublicGoIdRoute: typeof ApiPublicGoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it-it/': {
      id: '/it-it/'
      path: '/it-it'
      fullPath: '/it-it/'
      preLoaderRoute: typeof ItItIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/go/$id': {
      id: '/api/public/go/$id'
      path: '/api/public/go/$id'
      fullPath: '/api/public/go/$id'
      preLoaderRoute: typeof ApiPublicGoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ItItIndexRoute: ItItIndexRoute,
  ApiPublicGoIdRoute: ApiPublicGoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
